#include "../../../dssl/include/dssl-plugin.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
 * This file is intentionally verbose because its job is educational.
 *
 * The DSSL plugin API published in-tree is currently tiny:
 * - the host allocates or receives a DSSLTarget structure
 * - the plugin fills function pointers into that structure
 * - the host calls those callbacks while traversing a parsed DSSL file
 *
 * Important limitation:
 * The public header only exposes opaque ASTNode pointers, not a stable AST visitor API.
 * That means a portable plugin cannot safely inspect the full AST today.
 *
 * Instead of faking unsupported behavior, this sample demonstrates the parts that *are*
 * stable right now:
 * - target registration
 * - lifecycle management
 * - callback dispatch
 * - side-effectful output generation
 */

typedef struct MarkdownTargetState {
    FILE* out;
    unsigned int struct_count;
    unsigned int enum_count;
    unsigned int union_count;
    unsigned int rpc_count;
    unsigned int rest_count;
    unsigned int exec_count;
} MarkdownTargetState;

static void markdown_init(DSSLTarget* self, const char* out_dir) {
    MarkdownTargetState* state;
    char path[1024];

    if (self == NULL) {
        return;
    }

    state = (MarkdownTargetState*)calloc(1, sizeof(MarkdownTargetState));
    if (state == NULL) {
        return;
    }

    self->priv = state;

    /*
     * A real plugin would probably create one file per service.
     * This sample keeps things minimal and writes a single summary file.
     */
    snprintf(path, sizeof(path), "%s/%s", out_dir ? out_dir : ".", "dssl_markdown_index.md");
    state->out = fopen(path, "w");
    if (state->out == NULL) {
        free(state);
        self->priv = NULL;
        return;
    }

    fprintf(state->out, "# DSSL Markdown Index\n\n");
    fprintf(state->out, "This file was generated by the sample `markdown_index` plugin.\n\n");
    fprintf(state->out, "Because the public plugin ABI only exposes opaque AST pointers today,\n");
    fprintf(state->out, "this plugin records callback activity instead of walking internal AST fields.\n\n");
}

static void markdown_finalize(DSSLTarget* self) {
    MarkdownTargetState* state;
    if (self == NULL || self->priv == NULL) {
        return;
    }

    state = (MarkdownTargetState*)self->priv;
    if (state->out != NULL) {
        fprintf(state->out, "## Callback Summary\n\n");
        fprintf(state->out, "- structs seen: %u\n", state->struct_count);
        fprintf(state->out, "- enums seen: %u\n", state->enum_count);
        fprintf(state->out, "- unions seen: %u\n", state->union_count);
        fprintf(state->out, "- rpcs seen: %u\n", state->rpc_count);
        fprintf(state->out, "- rest endpoints seen: %u\n", state->rest_count);
        fprintf(state->out, "- exec commands seen: %u\n", state->exec_count);
        fclose(state->out);
    }
    free(state);
    self->priv = NULL;
}

static void markdown_emit_struct(DSSLTarget* self, ASTNode* node) {
    MarkdownTargetState* state = self != NULL ? (MarkdownTargetState*)self->priv : NULL;
    (void)node;
    if (state != NULL) {
        state->struct_count += 1;
    }
}

static void markdown_emit_enum(DSSLTarget* self, ASTNode* node) {
    MarkdownTargetState* state = self != NULL ? (MarkdownTargetState*)self->priv : NULL;
    (void)node;
    if (state != NULL) {
        state->enum_count += 1;
    }
}

static void markdown_emit_union(DSSLTarget* self, ASTNode* node) {
    MarkdownTargetState* state = self != NULL ? (MarkdownTargetState*)self->priv : NULL;
    (void)node;
    if (state != NULL) {
        state->union_count += 1;
    }
}

static void markdown_emit_rpc(DSSLTarget* self, ASTNode* node) {
    MarkdownTargetState* state = self != NULL ? (MarkdownTargetState*)self->priv : NULL;
    (void)node;
    if (state != NULL) {
        state->rpc_count += 1;
    }
}

static void markdown_emit_rest(DSSLTarget* self, ASTNode* node) {
    MarkdownTargetState* state = self != NULL ? (MarkdownTargetState*)self->priv : NULL;
    (void)node;
    if (state != NULL) {
        state->rest_count += 1;
    }
}

static void markdown_emit_exec(DSSLTarget* self, ASTNode* node) {
    MarkdownTargetState* state = self != NULL ? (MarkdownTargetState*)self->priv : NULL;
    (void)node;
    if (state != NULL) {
        state->exec_count += 1;
    }
}

DSSLTarget* dssl_plugin_create(void) {
    DSSLTarget* target = (DSSLTarget*)calloc(1, sizeof(DSSLTarget));
    if (target == NULL) {
        return NULL;
    }

    target->name = "markdown_index";
    target->init = markdown_init;
    target->finalize = markdown_finalize;
    target->emit_struct = markdown_emit_struct;
    target->emit_enum = markdown_emit_enum;
    target->emit_union = markdown_emit_union;
    target->emit_rpc = markdown_emit_rpc;
    target->emit_rest = markdown_emit_rest;
    target->emit_exec = markdown_emit_exec;
    return target;
}

void dssl_plugin_destroy(DSSLTarget* target) {
    if (target == NULL) {
        return;
    }

    /*
     * Defensive cleanup: if the host forgot to finalize, do it here too.
     * This keeps the sample simple and leak-resistant.
     */
    if (target->priv != NULL) {
        markdown_finalize(target);
    }
    free(target);
}
