#!/usr/bin/env python3
"""
DFC MkRecipe - Create or export DaffyChat room recipes

Recipes are Daffyscript files that define room configurations.
"""

import argparse
import json
import sys
from pathlib import Path


RECIPE_TEMPLATE = """// {recipe_name} room recipe
// Generated by dfc-mkrecipe

recipe {recipe_name} {{
    name = "{display_name}";
    description = "{description}";
    
    // Room configuration
    config {{
        max_users = {max_users};
        public = {public};
        persistent = {persistent};
    }}
    
    // Services to enable
    services {{
        // Add service configurations here
        // Example: enable("echo");
    }}
    
    // Initial setup
    on_create {{
        // Room initialization code
        log("Room created from {recipe_name} recipe");
    }}
}}
"""


def create_recipe(args):
    """Create a new recipe from template."""
    recipe_name = args.name.lower().replace(" ", "_")
    
    # Check output file
    output_path = Path(args.output)
    if output_path.exists() and not args.force:
        print(f"Error: File already exists: {output_path}", file=sys.stderr)
        print("Use --force to overwrite", file=sys.stderr)
        return 1
    
    # Create output directory
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Generate recipe content
    content = RECIPE_TEMPLATE.format(
        recipe_name=recipe_name,
        display_name=args.name,
        description=args.description or f"{args.name} room",
        max_users=args.max_users,
        public="true" if args.public else "false",
        persistent="true" if args.persistent else "false"
    )
    
    # Write file
    output_path.write_text(content)
    print(f"Created recipe: {output_path}")
    print(f"\nNext steps:")
    print(f"  1. Edit {output_path} to customize your room")
    print(f"  2. Compile: daffyscript compile {output_path}")
    print(f"  3. Use recipe when creating a room")
    
    return 0


def export_recipe(args):
    """Export an existing room configuration as a recipe."""
    # This would connect to a running DaffyChat instance
    # and export the room configuration
    print("Error: Export functionality requires a running DaffyChat instance", 
          file=sys.stderr)
    print("This feature is not yet implemented", file=sys.stderr)
    return 1


def main():
    parser = argparse.ArgumentParser(
        description="Create or export DaffyChat room recipes",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Create a new recipe
  %(prog)s create --name "Dev Team" --output recipes/dev_team.ds
  
  # Create a public, persistent room recipe
  %(prog)s create -n "Public Chat" -o recipes/public.ds --public --persistent
  
  # Export existing room (not yet implemented)
  %(prog)s export --room-id abc123 --output recipes/exported.ds
        """
    )
    
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # Create command
    create_parser = subparsers.add_parser("create", help="Create a new recipe")
    create_parser.add_argument("--name", "-n", required=True,
                              help="Recipe display name")
    create_parser.add_argument("--output", "-o", required=True,
                              help="Output file path")
    create_parser.add_argument("--description", "-d",
                              help="Recipe description")
    create_parser.add_argument("--max-users", type=int, default=50,
                              help="Maximum users (default: 50)")
    create_parser.add_argument("--public", action="store_true",
                              help="Make room public")
    create_parser.add_argument("--persistent", action="store_true",
                              help="Make room persistent")
    create_parser.add_argument("--force", "-f", action="store_true",
                              help="Overwrite existing file")
    
    # Export command
    export_parser = subparsers.add_parser("export", help="Export existing room")
    export_parser.add_argument("--room-id", required=True,
                              help="Room ID to export")
    export_parser.add_argument("--output", "-o", required=True,
                              help="Output file path")
    export_parser.add_argument("--force", "-f", action="store_true",
                              help="Overwrite existing file")
    
    args = parser.parse_args()
    
    if args.command == "create":
        return create_recipe(args)
    elif args.command == "export":
        return export_recipe(args)
    
    return 1


if __name__ == "__main__":
    sys.exit(main())
