#!/usr/bin/env python3
"""
DSSL Init - Scaffold a new DSSL service specification

Creates a template DSSL service with common patterns.
"""

import argparse
import sys
from pathlib import Path


DSSL_TEMPLATE = """/// {service_name} service specification
// Generated by dssl-init
service {service_name} 1.0.0;

/// Request payload for {service_name} service.
struct {request_type} {{
    message: string;
}}

/// Reply payload from {service_name} service.
struct {reply_type} {{
    message: string;
    success: bool;
}}

/// Process a request.
/// {description}
rpc Process(message: string) returns {reply_type};
"""


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a new DSSL service specification",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Create a new service spec
  %(prog)s --name myservice --output services/specs/myservice.dssl
  
  # Create with custom description
  %(prog)s --name auth --description "Authentication service" -o auth.dssl
        """
    )
    
    parser.add_argument("--name", "-n", required=True,
                       help="Service name (lowercase, no spaces)")
    parser.add_argument("--output", "-o", required=True,
                       help="Output file path")
    parser.add_argument("--description", "-d", 
                       default="Service description",
                       help="Service description")
    parser.add_argument("--force", "-f", action="store_true",
                       help="Overwrite existing file")
    
    args = parser.parse_args()
    
    # Validate service name
    service_name = args.name.lower().strip()
    if not service_name.isidentifier():
        print(f"Error: Invalid service name '{service_name}'", file=sys.stderr)
        print("Service name must be a valid identifier (letters, numbers, underscore)", 
              file=sys.stderr)
        return 1
    
    # Check output file
    output_path = Path(args.output)
    if output_path.exists() and not args.force:
        print(f"Error: File already exists: {output_path}", file=sys.stderr)
        print("Use --force to overwrite", file=sys.stderr)
        return 1
    
    # Create output directory
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Generate DSSL content
    request_type = f"{service_name.capitalize()}Request"
    reply_type = f"{service_name.capitalize()}Reply"
    
    content = DSSL_TEMPLATE.format(
        service_name=service_name,
        description=args.description,
        request_type=request_type,
        reply_type=reply_type
    )
    
    # Write file
    output_path.write_text(content)
    print(f"Created DSSL service specification: {output_path}")
    print(f"\nNext steps:")
    print(f"  1. Edit {output_path} to define your service")
    print(f"  2. Generate code: dssl-bindgen.py --target cpp --out-dir generated {output_path}")
    print(f"  3. Implement service logic in the generated skeleton file")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
